import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import Navbar from "@/components/common/navbar";
import AuthModal from "@/components/auth/auth-modal";
import { Bar } from "@/components/player/bar";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} antialiased`}>
      <body className="bg-foreground text-background">
        <Navbar />
        <Toaster
          position="top-center"
          toastOptions={{
            classNames: {
              success: "!bg-neutral-950 !border-green-800 !text-green-300",
              error: "!bg-red-950 !border-red-800 !text-red-300",
            },
          }}
        />
        <AuthModal />
        {children}
        <Bar />
      </body>
    </html>
  );
}
